### PR TITLE
Modify painting name and tooltips, and create unique textures for each painting item

### PR DESCRIPTION
**Pull request by Andrew6rant**
If CIT Resewn is installed, each painting will have a unique texture:

Texture Showcase

Tooltips are condensed down to one line.

Before:

Tooltip Showcase (Before)

After:

Tooltip Showcase (After)

I'm marking this as a draft because my tooltip code isn't the cleanest

### CODE REVIEW

**Comment by Estecka** [comment]
I'll move the thumbnails to the `minecraft` namespace. I think it makes more sense since those are extensions of vanilla items, and people could theorically make those changes without using the mod.

For the tooltip, I'd prefer having the size on the left side. That way it won't change position depending on the preceding text, and should be easier to find at a glance :
```
2x2 Painting (The Stage is Set)
Kristoffer Zetterstrand
```
or simply
```
2x2 The Stage is Set
Kristoffer Zetterstrand
```

**Comment by Estecka** [comment]
I made the change to have the size on the left of the author.
Other than that the code looks good to me.

**Comment by Andrew6rant** [comment]
Looks good to me! I do like the size on the left much better, thanks.
The only thing I changed was a bit of indent in `DecorationItemMixin`, to make it clearer that the `tooltip.add` call is not inside of the if statement

**Comment by Andrew6rant** [comment]
Whoops! I committed to the wrong branch. (since it is a different feature, I thought it best to PR separately)

Invalid Painting Showcase

**Comment by Estecka** [comment]
Yeah, go make a separate branch and PR with those change. I'll revert it back to [b6f4854](https://github.com/Estecka/mc-invariable-paintings/pull/3/commits/b6f48541e1e5f760608c8797b97e61a861e8de1c) later before merging.

**Pull request merged**
